;Skin information
Name=SetsujinStyle
Version=0.6.0
Creator=Ryuto Setsujin
Resolution=1920,1080
FontNameEN=Fonts/NotoSerifJP-Medium.ttf
FontNameJA=Fonts/NotoSerifJP-Medium.ttf
FontNameFR=Fonts/NotoSerifJP-Medium.ttf
FontNameES=Fonts/NotoSerifJP-Medium.ttf
FontNameNL=Fonts/NotoSerifJP-Medium.ttf
FontNameRU=Fonts/NotoSans-Medium.ttf
FontNameKO=Fonts/LINESeedKR-Rg.ttc
FontNameZH=Fonts/NotoSans-Medium.ttf
BoxFontNameEN=Fonts/NotoSerifJP-Regular.ttf
BoxFontNameJA=Fonts/NotoSerifJP-Regular.ttf
BoxFontNameFR=Fonts/NotoSerifJP-Regular.ttf
BoxFontNameES=Fonts/NotoSerifJP-Regular.ttf
BoxFontNameNL=Fonts/NotoSerifJP-Regular.ttf
BoxFontNameRU=Fonts/NotoSans-Regular.ttf
BoxFontNameKO=Fonts/LINESeedKR-Rg.ttc
BoxFontNameZH=Fonts/NotoSans-Regular.ttf


; "#include �t�@�C����" ���߂��g�����Ƃ�
; �O���t�@�C����ǂݍ���Ŏg�p���邱�Ƃ��ł���悤�ɂȂ�܂�
#include OtherConfig.ini
#include TitleConfig.ini
#include ConfigConfig.ini
#include SongSelectConfig.ini
#include DaniSelectConfig.ini
#include SongLoadingConfig.ini
#include GameConfig.ini
#include Game4PConfig.ini
#include ResultConfig.ini
#include Result4PConfig.ini
#include AIResultConfig.ini
#include DanResultConfig.ini
#include TowerResultConfig.ini
#include HeyaConfig.ini
#include OnlineLoungeConfig.ini
#include TowerSelectConfig.ini
#include OpenEncyclopediaConfig.ini
#include NamePlateConfig.ini
#include ModalConfig.ini
#include Modal4PConfig.ini